{% set name = "getdist" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmbant/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 91ab685946502ee11b8c5329ca06bf026e5786f900a83318008a3e98c97c749d

build:
  noarch: python
  entry_points:
    - getdist=getdist.command_line:getdist_command
    - getdist-gui=getdist.command_line:getdist_gui
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.17.0
    - matplotlib-base >=2.2.0,!=3.5.0
    - scipy >=1.5.0
    - pyyaml >=5.1
    - packaging

test:
  requires:
    - python {{ python_min }}
  commands:
    - getdist --version

about:
  home: https://github.com/cmbant/getdist
  summary: GetDist is a package for analysing Monte Carlo samples.
  description: |
    GetDist is a Python package for analysing Monte Carlo samples, including 
    correlated samples from Markov Chain Monte Carlo (MCMC).
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://getdist.readthedocs.io/

extra:
  recipe-maintainers:
    - cmbant
    - vitenti
    - marcpaterno
